-- Create tandas table if not exists
create table if not exists tandas (
  id bigint generated by default as identity primary key,
  nombre text unique not null,
  fecha date not null,
  parametros jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create entradas table if not exists
create table if not exists entradas (
  id bigint generated by default as identity primary key,
  tanda_nombre text references tandas(nombre) on delete cascade, -- referencing name as foreign key based on usage, though id is better practice, legacy seems to use name
  marca text not null,
  codigo_boleta text,
  producto_titulo text,
  cantidad_docenas numeric,
  precio_docena numeric,
  bultos numeric,
  codigo text,
  observaciones text,
  fotos text[], -- array of urls
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for performance
create index if not exists entradas_tanda_nombre_idx on entradas(tanda_nombre);
