-- Tabla para registrar ventas diarias mediante escáner QR
create table if not exists ventas (
  id bigint generated by default as identity primary key,
  fecha date not null default current_date,
  producto_titulo text not null,
  codigo text not null,
  propietario text,
  cantidad_docenas numeric not null,
  precio_docena_ars numeric not null,
  total_ars numeric not null,
  dolar_blue numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table ventas enable row level security;

create policy "ventas_all" on ventas for all using (true);

create index if not exists ventas_fecha_idx on ventas(fecha);
create index if not exists ventas_codigo_idx on ventas(codigo);
